# Generated by Django 5.0.2 on 2024-02-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
